// A small bundled CycloneDX 1.5 sample so "Load sample SBOM" works without a file.
// It is sent through POST /api/parse like any other input.
export const SAMPLE_SBOM = {
  bomFormat: "CycloneDX",
  specVersion: "1.5",
  serialNumber: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79",
  version: 1,
  metadata: {
    timestamp: "2026-01-15T12:00:00Z",
    tools: [{ vendor: "syft", name: "syft", version: "1.0.0" }],
    component: {
      "bom-ref": "root-app",
      type: "application",
      name: "acme-web",
      version: "2.3.0",
    },
  },
  components: [
    {
      "bom-ref": "comp-lodash",
      type: "library",
      name: "lodash",
      version: "4.17.11",
      purl: "pkg:npm/lodash@4.17.11",
      licenses: [{ license: { id: "MIT" } }],
      supplier: { name: "OpenJS Foundation" },
      description: "Lodash modular utilities.",
    },
    {
      "bom-ref": "comp-express",
      type: "framework",
      name: "express",
      version: "4.17.1",
      purl: "pkg:npm/express@4.17.1",
      licenses: [{ license: { id: "MIT" } }],
      supplier: { name: "OpenJS Foundation" },
      description: "Fast, unopinionated, minimalist web framework.",
    },
    {
      "bom-ref": "comp-minimist",
      type: "library",
      name: "minimist",
      version: "1.2.0",
      purl: "pkg:npm/minimist@1.2.0",
      licenses: [{ license: { id: "MIT" } }],
      supplier: { name: "substack" },
      description: "Parse argument options.",
    },
    {
      "bom-ref": "comp-jinja2",
      type: "library",
      name: "jinja2",
      version: "2.10",
      purl: "pkg:pypi/jinja2@2.10",
      licenses: [{ license: { id: "BSD-3-Clause" } }],
      supplier: { name: "Pallets" },
      description: "A very fast and expressive template engine.",
    },
    {
      "bom-ref": "comp-requests",
      type: "library",
      name: "requests",
      version: "2.20.0",
      purl: "pkg:pypi/requests@2.20.0",
      licenses: [{ license: { id: "Apache-2.0" } }],
      supplier: { name: "Python Software Foundation" },
      description: "Python HTTP for Humans.",
    },
    {
      "bom-ref": "comp-log4j",
      type: "library",
      name: "log4j-core",
      version: "2.14.1",
      purl: "pkg:maven/org.apache.logging.log4j/log4j-core@2.14.1",
      licenses: [{ license: { id: "Apache-2.0" } }],
      supplier: { name: "Apache Software Foundation" },
      description: "Apache Log4j Core.",
    },
    {
      "bom-ref": "comp-internal",
      type: "library",
      name: "acme-internal-utils",
      version: "0.1.0",
      purl: "",
      licenses: [],
      supplier: { name: "Acme Corp" },
      description: "Internal helper library (no public license).",
    },
  ],
  dependencies: [
    { ref: "root-app", dependsOn: ["comp-express", "comp-requests", "comp-log4j", "comp-internal"] },
    { ref: "comp-express", dependsOn: ["comp-lodash", "comp-minimist"] },
    { ref: "comp-requests", dependsOn: ["comp-jinja2"] },
    { ref: "comp-internal", dependsOn: ["comp-lodash"] },
  ],
};
